version: '3'

services:
  web:
    build: .
    links:
      - rabbitmq:rabbitmq
    command: bash -c "celery -A task.task worker --app=task.task:celery_app -l info"
    volumes:
      - ./code:/code
    environment:
      - CELERY_BROKER_URL=amqp://myuser:mypass@rabbitmq:5672/myvhost

  rabbitmq:
      image: rabbitmq:3.7-management
      ports:
        - "8031:15672"
        - "5672:5672"
        - "5671:5671"
      environment:
        - RABBITMQ_DEFAULT_PASS=mypass
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_VHOST=myvhost
